//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПРАКТИКА_MVC_ПРИЛОЖЕНИЕ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Адрес_пациента> Адрес_пациента { get; set; }
        public virtual DbSet<Врач> Врач { get; set; }
        public virtual DbSet<Диагнозы_за_осмотр> Диагнозы_за_осмотр { get; set; }
        public virtual DbSet<Идентификатор_врача> Идентификатор_врача { get; set; }
        public virtual DbSet<Карточка_представителя> Карточка_представителя { get; set; }
        public virtual DbSet<Логин_и_пароль> Логин_и_пароль { get; set; }
        public virtual DbSet<Назначения_препаратов> Назначения_препаратов { get; set; }
        public virtual DbSet<Осмотр_пациента> Осмотр_пациента { get; set; }
        public virtual DbSet<Родственная_связь> Родственная_связь { get; set; }
        public virtual DbSet<Связь_пациента_с_представителем> Связь_пациента_с_представителем { get; set; }
        public virtual DbSet<Специализация_врача> Специализация_врача { get; set; }
        public virtual DbSet<Учреждение_здравоохранения> Учреждение_здравоохранения { get; set; }
        public virtual DbSet<Электронная_амбулаторная_карта> Электронная_амбулаторная_карта { get; set; }
    }
}
