//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПРАКТИКА_MVC_ПРИЛОЖЕНИЕ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Врач
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Врач()
        {
            this.Идентификатор_врача = new HashSet<Идентификатор_врача>();
        }
    
        public int Код_врача { get; set; }
        public int Код_учреждения_здравоохранения { get; set; }
        public string Рабочий_телефон { get; set; }
        public string Фамилия_врача { get; set; }
        public string Имя_врача { get; set; }
        public string Отчество_врача { get; set; }
    
        public virtual Учреждение_здравоохранения Учреждение_здравоохранения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Идентификатор_врача> Идентификатор_врача { get; set; }
    }
}
