//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПРАКТИКА_MVC_ПРИЛОЖЕНИЕ.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Идентификатор_врача
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Идентификатор_врача()
        {
            this.Осмотр_пациента = new HashSet<Осмотр_пациента>();
        }
    
        public int Идентификатор_врача1 { get; set; }
        public int Код_врача { get; set; }
        public int Код_специальности { get; set; }
        public string Категория { get; set; }
    
        public virtual Врач Врач { get; set; }
        public virtual Специализация_врача Специализация_врача { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Осмотр_пациента> Осмотр_пациента { get; set; }
        public IEnumerable<SelectListItem> DoctorList { get; set; }

    }
}
