//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПРАКТИКА_MVC_ПРИЛОЖЕНИЕ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Карточка_представителя
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Карточка_представителя()
        {
            this.Связь_пациента_с_представителем = new HashSet<Связь_пациента_с_представителем>();
        }
    
        public int Код_представителя { get; set; }
        public string Фамилия_представителя { get; set; }
        public string Имя_представителя { get; set; }
        public string Отчество_представителя { get; set; }
        public Nullable<decimal> Серия_и_номер_паспорта { get; set; }
        public string Место_работы { get; set; }
        public string Контактный_телефон_представителя { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Связь_пациента_с_представителем> Связь_пациента_с_представителем { get; set; }
    }
}
