//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПРАКТИКА_MVC_ПРИЛОЖЕНИЕ.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Осмотр_пациента
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Осмотр_пациента()
        {
            this.Диагнозы_за_осмотр = new HashSet<Диагнозы_за_осмотр>();
            this.Назначения_препаратов = new HashSet<Назначения_препаратов>();
        }
    
        public int Номер_осмотра { get; set; }
        public int Номер_амбулаторной_карты { get; set; }
        public int Идентификатор_врача { get; set; }
        public System.DateTime Дата_приема { get; set; }
        public string Цель_посещения { get; set; }
        public bool Повторный_прием { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Диагнозы_за_осмотр> Диагнозы_за_осмотр { get; set; }
        public virtual Идентификатор_врача Идентификатор_врача1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Назначения_препаратов> Назначения_препаратов { get; set; }
        public virtual Электронная_амбулаторная_карта Электронная_амбулаторная_карта { get; set; }
        public IEnumerable<SelectListItem> SpecialtyList { get; set; }
        public IEnumerable<SelectListItem> PatientList { get; set; }
        public IEnumerable<SelectListItem> DoctorList { get; set; }
    }
}
