//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПРАКТИКА_MVC_ПРИЛОЖЕНИЕ.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Связь_пациента_с_представителем
    {
        public int Код_родственной_связи { get; set; }
        public int Номер_амбулаторной_карты_пациента { get; set; }
        public int Код_представителя { get; set; }
        public int Родственная_связь { get; set; }
    
        public virtual Карточка_представителя Карточка_представителя { get; set; }
        public virtual Родственная_связь Родственная_связь1 { get; set; }
        public virtual Электронная_амбулаторная_карта Электронная_амбулаторная_карта { get; set; }
        public IEnumerable<SelectListItem> CategoryList { get; set; }
        public IEnumerable<SelectListItem> PatientList { get; set; }
        public IEnumerable<SelectListItem> ParentList { get; set; }



    }
}
